### PR TITLE
Flycheck was not using jdee classpath, but now it does

### PR DESCRIPTION
**Pull request by marciosmiderle**
Flycheck is not using jdee classpath variables that a project could have set. This leads to flycheck indicate errors that actually do not exist.
With this change flycheck now works better. Fell free to change this patch as you wish.

### CODE REVIEW

**Comment by pwojnowski** [comment]
Hi! I was sitting on this for a while and couldn't reproduce this issue. Could you provide minimum project settings to recreate the issue?

**Comment by marciosmiderle** [comment]
Hi,

Steps to reproduce issue 121:

Unzip the attached project into a temporary directory. It is a netbeans project with an ant script independent from IDE.

1. Open Produto.java and Agencia.java. It is ok flyckeck show error "cannot find symbol" for Agencia line in Produto.java (neither are compiled).
2. C-c C-v C-c in Produto.java: compile error since Produto.java depends on Agencia.java that is not built.
3. C-c ! c in Produto.java: it is still ok flyckeck show error "cannot find symbol" for Agencia line in Produto.java. Agencia.java is not built.
4. C-c C-v C-c in Agencia.java: compilation ok. Agencia.class is saved in jdee-built-class-path (build/classes/produtosmetas).
5. C-c ! c in Produto.java: flyckeck incorrectly shows error "cannot find symbol" for Agencia line in Produto.java. It is wrong because in jdee-built-class-path Agencia.class was just built and is present.

If you follow these steps again with the patch, in the last step flycheck does not show any error as expected.

[Produtos Metas.tar.gz](https://github.com/jdee-emacs/jdee/files/954082/Produtos.Metas.tar.gz)

**Comment by pwojnowski** [comment]
Thank you very much for the project and good description! :+1: 

I look at it and the problem is that in your prj.el file, the JDEE variables that handle classpaths (jdee-built-class-path, jdee-sourcepath, etc.) are specified as buffer local variables. This is the reason why flycheck couldn't reuse them. When I commented out the lines with ```make-local-variable``` then Flycheck works as expected.

Is there any reason for making the variables buffer local?

**Comment by marciosmiderle** [comment]
The reason is that I needed to work in more than one project at the same time (it were two projects with one calling the other's interfaces and their bugs). If I didn't make the variables buffer local their class paths got mixed, the required libraries could be mixed and, worse, the output classes ended up in the wrong project built class path! It is enough to make the variables project/dir local but, as far as I know, emacs don't provide this concept for a file in a temporary directory.
I know that copying all var is not that beauty, so can't you compile the file changing just and temporarily the output path (jdee built class path)? It would not need a temporary file and the outcome would be the same.

**Comment by pwojnowski** [comment]
JDEE has project context switching, controlled by ```jdee-project-context-switching-enabled-p``` variable. Make sure it is set to ```t``` (default value). This makes JDEE reload variables from project files whenever you switch between Java files in different project. When you have ```jdee-compile-option-directory``` set in both projects, then it will be changed every time you switch between projects, so classes will be compiled into directories defined in project files. The same with ```jdee-built-class-path```.
Similarly, JDEE Server keeps loaded classes separated for each project.
So, if some variable is not changing when you change projects and you see some misbehavior, then please report it as a bug and I'll look at it.

**Comment by marciosmiderle** [comment]
Ok, I will change my scripts and set up the context switch variable. Thanks.

**Pull request closed without merging**
